### ISSUE TITLE
It this project still alive?

### ISSUE THREAD

**Issue by cxwx** [maryheintz/vme#1]
It seems that this version vme_universe compile one new linux kernel > 2.6.19 is broken.

file linux/config.h not found

VM_SHM undeclared 

and so on.  Many kernel problems.

could someon recomend a linux version which is still alive with old kernel? like fedora or ubuntu, centos? or The driver has some new version?

**Comment by jeisch** [comment]
RHEL/CentOS/Scientific 4.9 should work well.

**Comment by maryheintz** [comment]
We have only ever used this driver on systems running Scientific Linux 4.7.  The kernel on the system that we're currently using is:
Linux edgcrate1 2.6.9-78.0.1.EL #1 Tue Aug 5 12:35:58 CDT 2008 i686 i686 i386 GNU/Linux

Any information that I had about setting all of this up is here:  http://edg.uchicago.edu/projects/vme7648/
